### ISSUE TITLE
redis-py version in setup.py too restrictive?

### ISSUE THREAD

**Issue by YAmikep** [hellp/saferedisqueue#3]
Hi,

First, thank you for this library, it's very nice.

I see that in the install script setup.py, you force redis-py to be a specific version: `redis >= 2.7.6, < 2.10.2`

I think it would be better to not be that restrictive and let the minor versions out of the scope: `< 2.11`

I have redis-py 2.10.4 and you can see that the changes in the minor versions 2.10.x are only bug fixes compare to the 2.10.0 version (https://github.com/andymccurdy/redis-py/blob/master/CHANGES) so the risk of a regression is very low.

Let me know what you think.
Thanks

Michael

**Comment by hellp** [comment]
Yes, I guess I'd like to go for "<2.11" too. On the other hand the changelog for redis-py 2.10.2 mentions a "POSSIBLE BACKWARDS INCOMPATBLE CHANGE" – not what you would expect in a minor update ;)

I'll test it tomorrow and do a release then. I think allowing the minor versions to increase is "the right thing" to do. If something breaks, we can react; also everyone should pin full versions in their project's requirements.txt or buildout config, imho, anyway.

May I ask in what kind of project you are using saferedisqueue?

**Comment by YAmikep** [comment]
Yes, you are right, the fact that there could be some backwards incompatible changes in a minor update is definitely not great but as you pointed out, everybody should pin full versions in their project's requirements anyway so allowing the minor versions is ok.

I am working on a website and I needed a reliable distributed queue to make sure each message is processed.

Thanks

**Comment by hellp** [comment]
on master. release ETA 2014-11-08

**Comment by YAmikep** [comment]
@hellp 
Ok thanks. Do you think you can also include in the release the support for the optional serializer and maybe the "get/put" compatibility? You have not given your thoughts on this one though. Let me know what you think.

Thanks

**Comment by YAmikep** [comment]
@hellp 
Any chance that a new version is released soon with the changes we have been talking about?
Thanks

**Comment by hellp** [comment]
released 3.0.0
