### ISSUE TITLE
push/pop terminology?

### ISSUE THREAD

**Issue by YAmikep** [hellp/saferedisqueue#5]
Hi Fabian,

I wanted to discuss about the terminology you use to add/remove elements from the queue.

At first, I was confused to use `push/pop` because it suggests a stack data structure instead of a queue. I thought it was my understanding but googling it confirmed that `push/pop` are more stack (first in last out) operations

`put/get` are more suited for FIFO queue operations. The queue of python itself uses this terminology (https://docs.python.org/2/library/queue.html#Queue.Queue.put), it might be a good idea to be consistent. This would avoid any confusions when someone already uses python standard queues.

It is not required to remove `push/pop` right away, they can stay for backwards compatibility until you decide to remove them.

``` python
def put():
    ...
push = put

def get():
    ...
pop = get
```

Just a thought.
Let me know what you think

Thanks
Michael

**Comment by YAmikep** [comment]
Also, I think it would make sense to `return uid` in `push`/`put` so that we get the reference of the item we just added to the queue in case we need it.

``` python
def put():
    ...
    return uid
push = put
```

**Comment by hellp** [comment]
Good idea. Does this qualify for a major version update then? Technically it's a change of the public API.

**Comment by YAmikep** [comment]
Yes, that could be a major version. It can include the other changes I proposed as well if you want.
Thanks
